package org.example.model;

public enum Type {
    VOID,

    LOGIN,
    SIGNUP,
    SUCCESS,
    ERROR,
    NEW_GAME,
    LEADERBOARD,
    REACTION,
    CREATE_LOBBY,
    SEND_INVITATION,
    INVITATION,
    ACCEPT_INVITATION,
    TICK,
    CREATE_GAME,
    GAME_CREATED,

    START_GAME,
    JOIN_LOBBY,
    CHOOSE_MAP,
    CHOOSE_NAME_GENDER,
    REQUEST_JOIN,
    REQUEST_LEAVE_LOBBY,
    LEAVE_LOBBY,
    PLAYER_MOVE,

    ENTITY_UPDATE,
    SEND_MESSAGE,
    SHOW_CHAT,
    MESSAGE,

    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_NICKNAME,
    CHANGE_EMAIL,
    CHANGE_GENDER,
    ;
}
