package org.example.model.consts;

public enum Type {
    VOID,

    LOGIN,
    SIGNUP,
    SUCCESS,
    ERROR,
    NEW_GAME,
    LEADERBOARD,
    REACTION,
    CREATE_LOBBY,
    SEND_INVITATION,
    INVITATION,
    ACCEPT_INVITATION,
    TICK,
    CREATE_GAME,
    GAME_CREATED,

    START_GAME,
    JOIN_LOBBY,
    CHOOSE_MAP,
    CHOOSE_NAME_GENDER,
    REQUEST_JOIN,
    REQUEST_LEAVE_LOBBY,
    LEAVE_LOBBY,
    PLAYER_MOVE,
    NPC_MOVE,

    ENTITY_UPDATE,
    SEND_MESSAGE,
    SHOW_CHAT,
    MESSAGE,

    CHANGE_USERNAME,
    CHANGE_PASSWORD,
    CHANGE_NICKNAME,
    CHANGE_EMAIL,
    CHANGE_GENDER,

    START_BROADCASTING,
    AUDIO_CHUNK,
    JOIN_RADIO,
    LEAVE_RADIO,
    SEND_AUDIO_CHUNK,
    RADIO_LIST,

    CHANGE_TILE,
    LOBBY_LIST,
    PLAYER_LIST,

    START_VOTE_FIRE,
    START_VOTE_FORCE_TERMINATE,

    VOTE_FORCE_TERMINATE_STARTED,
    VOTE_FIRE_STARTED,

    VOTE_FORCE_TERMINATE,
    VOTE_FIRE,

    TERMINATED,
    FIRED,

    MEET_NPC,
    GIFT_NPC,
    GET_QUEST,
    COMPLETE_QUEST,
    QUEST_LIST,
    NPC_RELATION_LIST,

    SHOP_ITEM_LIST,
    BUY_ITEM,

    ;
}
